[ERROR] /opt/cloudstack-sources/plugins/storage/object/huawei-obs/src/main/java/org/apache/cloudstack/storage/datastore/driver/HuaweiObsObjectStoreDriverImpl.java:[203,16] error: cannot find symbol [ERROR]   symbol:   method HEAD() [ERROR]   location: interface Builder
was caused by JDK21 being installed on my machine and even though I configured the project to adhere to JDK11 rules, it accepts the HEAD() method as valid even though it is not available through JDK11